name: Build and Release Feather (idevice)

on:
  push:
    branches:
      - main
    types:
      - committed  
  workflow_dispatch:

jobs:
  build-feather-idevice:
    runs-on: macos-latest
    continue-on-error: true 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Generate release metadata
        id: meta
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "TAG=featherrelease-${SHORT_SHA}" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=Feather Rewrite Test Release $SHORT_SHA" >> "$GITHUB_ENV"

      - name: Archive Build (Unsigned)
        run: |
          xcodebuild clean archive \
            -project Feather.xcodeproj \
            -scheme "Feather (idevice)" \
            -configuration Release \
            -archivePath build/FeatherIdevice.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH=YES \
            ARCHS=arm64 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_OPTIMIZATION_LEVEL="-Owholemodule" \
            IPHONEOS_DEPLOYMENT_TARGET=17.4 \
            -skipPackagePluginValidation

      - name: Create unsigned IPA
        run: |
          mkdir -p build/Payload
          APP_PATH="build/FeatherIdevice.xcarchive/Products/Applications/Feather (idevice).app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App not found at expected path: $APP_PATH"
            exit 1
          fi
          cp -R "$APP_PATH" build/Payload/
          cd build
          zip -r Feather-idevice.ipa Payload

      - name: Upload IPA (Create or Update Release)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: build/Feather-idevice.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
